SELECT A.ID
FROM (
        SELECT A.ID
            , A.RECORDDATE
            , A.TEMPERATURE
            , LAG(A.RECORDDATE) OVER(ORDER BY A.RECORDDATE) AS YESTERDAY
            , LAG(A.TEMPERATURE) OVER(ORDER BY A.RECORDDATE) AS YESTER_TEMP
        FROM WEATHER A
    ) A
WHERE A.TEMPERATURE > A.YESTER_TEMP
AND A.RECORDDATE = A.YESTERDAY + 1
;