SELECT NVL(SALARY, NULL) AS SECONDHIGHESTSALARY
-- (CASE WHEN SALARY IS NULL
--          THEN SALARY
--          ELSE NULL
--    END ) AS SECONDHIGHESTSALARY
FROM (
    SELECT RANK() OVER (ORDER BY SALARY DESC) AS RNK, SALARY
    FROM EMPLOYEE
) A
WHERE A.RNK = 2
;
