# Write your MySQL query statement below


## Oracle
# WITH PERSON2 AS (
# SELECT MIN(PP.ID)
# FROM PERSON PP
# GROUP BY EMAIL
# )
# DELETE FROM PERSON P1
# WHERE P1.ID NOT IN (SELECT P2.* FROM PERSON2 P2)

DELETE P1 FROM PERSON P1, PERSON P2
WHERE P1.EMAIL = P2.EMAIL
AND P1.ID > P2.ID